[app]
examc-prod ansible_host=examc.epfl.ch ansible_user=root ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
